name: BACKEND - API Service Test

on:
  push:
    branches:
      - main
      - workflow-github
  pull_request:
    branches:
      - main
      - workflow-github

jobs:
  test:
    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: tool/backend
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Setup uv
        uses: astral-sh/setup-uv@v5
        with:
          enable-cache: true

      - name: Install dependencies
        run: uv sync --frozen

      - name: Run tests
        run: uv run pytest
